FROM apache/spark:3.5.3

USER root
RUN apt-get update && apt-get install -y python3 python3-pip && \
    ln -s /usr/bin/python3 /usr/bin/python && \
    pip install numpy pandas scikit-learn influxdb-client
USER spark